[react-accordion] Allow disabled `AccordionItem` when `Accordion` is `disabled={false}`
radix-ui/primitives pull request #400
Opened 2021-01-14 17:25 UTC by jjenzz

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code.
- [X] Add or edit tests to reflect the change (run `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (run `yarn dev`).
- [ ] Add documentation to support any new features.

This pull request:

- [X] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [ ] Other

2021-01-14 18:56 UTC, chaance requested changes
Looks good to me! Think we can go ahead and add a `CHANGELOG` here per the Slack conversation?

2021-01-14 20:34 UTC, benoitgrelard approved these changes

2021-01-15 14:17 UTC, jjenzz commented
@chaance There is no `CHANGELOG` file so I'm not really sure what the plan is there. 

We should probably create a separate CHANGELOG PR with everything merged since last release that demonstrates the format we can follow. I'm not sure if we want a `CHANGELOG` per package or just in the root for example so this is all stuff we can probably solve separately and then each PR would follow it once merged?

2021-01-15 14:34 UTC, benoitgrelard commented
Yeah I was going to say I think this is something we should start after we do our next release with all the changes that are currently queued up already.

2021-01-15 17:24 UTC, chaance approved these changes

2021-01-15 20:09 UTC, merged